version: "3"
services:

  bot:
    image: "joaomsimoes/telegram-bot:latest"
    restart: on-failure

  index-api:
    image: "joaomsimoes/index:latest"
    # TO USE GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - bot
